parameters:
  - name: Artifacts
    type: object
    default: []
  - name: ServiceDirectory
    type: string
    default: not-specified
  - name: TestPipeline
    type: boolean
    default: false
  - name: CtestRegex
    type: string
    default: .*
  - name: CoverageReportPath
    type: string
    default: 'sdk/*/*/*cov_xml.xml'

jobs:
  - job: Validate_${{ machine.Key }}
    condition: and(succeededOrFailed(), ne(variables['Skip.Test'], 'true'))
    pool:
      name: ${{ machine.Value.Pool }}
      vmImage: ${{ machine.Value.OsVmImage }}

    variables:
    - name: CMOCKA_XML_FILE
      value: "%g-test-results.xml"
    - name: CMOCKA_MESSAGE_OUTPUT
      value: "xml"
    - name: BuildArgs
      value: ""
    - name: CmakeEnvArg
      value: ""
    - name: CmakeArgs
      value: ""
    - name: AZURE_TEST_MODE
      value: "PLAYBACK"
    # Compatibility with the old build architecture
    # TODO: Eliminate this and use template logic to shorten the number of
    # steps instead.
    - name: OSVmImage
      value: ${{ parameters.Value.OsVmImage }}

    steps:
      - template:
        /eng/pipelines/templates/steps/ci.yml